import { hexToRgb } from './colorConversion';

interface ColorNameItem {
  name: string;
  hex: string;
}

// 180+ curated colors representing distinct beautiful shades
const COLOR_DICTIONARY: ColorNameItem[] = [
  { name: 'Absolute Zero', hex: '#0048BA' },
  { name: 'Acid Green', hex: '#B0BF1A' },
  { name: 'Aero', hex: '#7CB9E8' },
  { name: 'Alabaster', hex: '#F2F0EA' },
  { name: 'Alice Blue', hex: '#F0F8FF' },
  { name: 'Alizarin Crimson', hex: '#E32636' },
  { name: 'Alloy Orange', hex: '#C46210' },
  { name: 'Almond', hex: '#EFDECD' },
  { name: 'Amber', hex: '#FFBF00' },
  { name: 'Amethyst', hex: '#9966CC' },
  { name: 'Anti-Flash White', hex: '#F4F4F4' },
  { name: 'Antique Brass', hex: '#CD9575' },
  { name: 'Antique Bronze', hex: '#665D1E' },
  { name: 'Antique White', hex: '#FAEBD7' },
  { name: 'Aqua', hex: '#00FFFF' },
  { name: 'Aquamarine', hex: '#7FFFD4' },
  { name: 'Arctic Lime', hex: '#D0FF14' },
  { name: 'Army Green', hex: '#4B5320' },
  { name: 'Ash Gray', hex: '#B2BEB5' },
  { name: 'Asparagus', hex: '#87A96B' },
  { name: 'Atomic Tangerine', hex: '#FF9966' },
  { name: 'Auburn', hex: '#A17A74' },
  { name: 'Aureolin', hex: '#FDEE00' },
  { name: 'Avocado', hex: '#568203' },
  { name: 'Azure', hex: '#007FFF' },
  { name: 'Baby Blue', hex: '#89CFF0' },
  { name: 'Baby Pink', hex: '#F4C2C2' },
  { name: 'Baker-Miller Pink', hex: '#FF91AF' },
  { name: 'Banana Mania', hex: '#FAE7B5' },
  { name: 'Barbie Pink', hex: '#DA1884' },
  { name: 'Barn Red', hex: '#7C0A02' },
  { name: 'Battleship Grey', hex: '#848482' },
  { name: 'Beaver', hex: '#9F8170' },
  { name: 'Beige', hex: '#F5F5DC' },
  { name: 'Bisque', hex: '#FFE4C4' },
  { name: 'Bistre', hex: '#3D0C02' },
  { name: 'Bitter Lemon', hex: '#CAE00D' },
  { name: 'Bittersweet', hex: '#FE6F5E' },
  { name: 'Black', hex: '#000000' },
  { name: 'Blanched Almond', hex: '#FFEBCD' },
  { name: 'Blast-Off Bronze', hex: '#A57164' },
  { name: 'Bleu de France', hex: '#318CE7' },
  { name: 'Blizzard Blue', hex: '#ACE5EE' },
  { name: 'Blond', hex: '#FAF0BE' },
  { name: 'Blood Red', hex: '#660000' },
  { name: 'Blue', hex: '#0000FF' },
  { name: 'Blue-Gray', hex: '#6699CC' },
  { name: 'Blue-Green', hex: '#0D98BA' },
  { name: 'Blue-Violet', hex: '#8A2BE2' },
  { name: 'Blueberry', hex: '#4F86F7' },
  { name: 'Blush', hex: '#DE5D83' },
  { name: 'Bole', hex: '#79443B' },
  { name: 'Bone', hex: '#E3DAC9' },
  { name: 'Bottle Green', hex: '#006A4E' },
  { name: 'Brandeis Blue', hex: '#0070FF' },
  { name: 'Brick Red', hex: '#CB4154' },
  { name: 'Bright Green', hex: '#66FF00' },
  { name: 'Bright Lavender', hex: '#BF94E4' },
  { name: 'Bright Lilac', hex: '#D891EF' },
  { name: 'Bright Navy Blue', hex: '#1974D2' },
  { name: 'Bright Yellow', hex: '#FFAA1D' },
  { name: 'Bronze', hex: '#CD7F32' },
  { name: 'Brown', hex: '#964B00' },
  { name: 'Bud Green', hex: '#7BB661' },
  { name: 'Buff', hex: '#F0DC82' },
  { name: 'Burgundy', hex: '#800020' },
  { name: 'Burlywood', hex: '#DEB887' },
  { name: 'Burnished Brown', hex: '#A17A74' },
  { name: 'Burnt Orange', hex: '#CC5500' },
  { name: 'Burnt Sienna', hex: '#E97451' },
  { name: 'Burnt Umber', hex: '#8A3324' },
  { name: 'Byzantine', hex: '#BD33A4' },
  { name: 'Byzantium', hex: '#702963' },
  { name: 'Cadet Blue', hex: '#5F9EA0' },
  { name: 'Cadet Grey', hex: '#91A3B0' },
  { name: 'Cadmium Green', hex: '#006B3C' },
  { name: 'Cadmium Orange', hex: '#ED872D' },
  { name: 'Cadmium Red', hex: '#E30022' },
  { name: 'Cadmium Yellow', hex: '#FFF600' },
  { name: 'Café au Lait', hex: '#A67B5B' },
  { name: 'Café Noir', hex: '#4B3621' },
  { name: 'Calypso', hex: '#317873' },
  { name: 'Camel', hex: '#C19A6B' },
  { name: 'Cameo Pink', hex: '#EFBBCC' },
  { name: 'Canary Yellow', hex: '#FFEF00' },
  { name: 'Candy Apple Red', hex: '#FF0800' },
  { name: 'Candy Pink', hex: '#E4717A' },
  { name: 'Capri', hex: '#00BFFF' },
  { name: 'Cardinal', hex: '#C41E3A' },
  { name: 'Caribbean Green', hex: '#00CC99' },
  { name: 'Carmine', hex: '#960018' },
  { name: 'Carnation Pink', hex: '#FFA6C9' },
  { name: 'Carnelian', hex: '#B31B1B' },
  { name: 'Carolina Blue', hex: '#56A0D3' },
  { name: 'Carrot Orange', hex: '#ED9121' },
  { name: 'Celadon', hex: '#ACE1AF' },
  { name: 'Celeste', hex: '#B2FFFF' },
  { name: 'Cerise', hex: '#DE3163' },
  { name: 'Cerulean', hex: '#007BA7' },
  { name: 'Chambray', hex: '#354E8C' },
  { name: 'Champagne', hex: '#F7E7CE' },
  { name: 'Charcoal', hex: '#36454F' },
  { name: 'Chartreuse', hex: '#7FFF00' },
  { name: 'Cherry Blossom Pink', hex: '#FFB7C5' },
  { name: 'Chestnut', hex: '#954535' },
  { name: 'Chocolate', hex: '#7B3F00' },
  { name: 'Cinnabar', hex: '#E34234' },
  { name: 'Cinnamon Satchel', hex: '#9B4722' },
  { name: 'Citrine', hex: '#E4D96F' },
  { name: 'Cobalt Blue', hex: '#0047AB' },
  { name: 'Coconut', hex: '#965A3E' },
  { name: 'Coffee', hex: '#6F4E37' },
  { name: 'Columbia Blue', hex: '#B9D9EB' },
  { name: 'Cool Grey', hex: '#8C92AC' },
  { name: 'Copper', hex: '#B87333' },
  { name: 'Coral', hex: '#FF7F50' },
  { name: 'Coral Red', hex: '#FF4040' },
  { name: 'Cornflower Blue', hex: '#6495ED' },
  { name: 'Cornsilk', hex: '#FFF8DC' },
  { name: 'Cosmic Cobalt', hex: '#2E2D88' },
  { name: 'Cotton Candy', hex: '#FFBCD9' },
  { name: 'Cream', hex: '#FFFDD0' },
  { name: 'Crimson', hex: '#DC143C' },
  { name: 'Cyan', hex: '#00FFFF' },
  { name: 'Dandelion', hex: '#F0E130' },
  { name: 'Dark Blue', hex: '#00008B' },
  { name: 'Dark Brown', hex: '#654321' },
  { name: 'Dark Cyan', hex: '#008B8B' },
  { name: 'Dark Goldenrod', hex: '#B8860B' },
  { name: 'Dark Gray', hex: '#A9A9A9' },
  { name: 'Dark Green', hex: '#013220' },
  { name: 'Dark Khaki', hex: '#BDB76B' },
  { name: 'Dark Magenta', hex: '#8B008B' },
  { name: 'Dark Olive Green', hex: '#556B2F' },
  { name: 'Dark Orange', hex: '#FF8C00' },
  { name: 'Dark Orchid', hex: '#9932CC' },
  { name: 'Dark Red', hex: '#8B0000' },
  { name: 'Dark Salmon', hex: '#E9967A' },
  { name: 'Dark Sea Green', hex: '#8FBC8F' },
  { name: 'Dark Slate Blue', hex: '#483D8B' },
  { name: 'Dark Slate Gray', hex: '#2F4F4F' },
  { name: 'Dark Turquoise', hex: '#00CED1' },
  { name: 'Dark Violet', hex: '#9400D3' },
  { name: 'Deep Peach', hex: '#FFCBA4' },
  { name: 'Deep Purple', hex: '#36013F' },
  { name: 'Deep Sky Blue', hex: '#00BFFF' },
  { name: 'Deuteranope Red', hex: '#C2A200' },
  { name: 'Dim Gray', hex: '#696969' },
  { name: 'Dodger Blue', hex: '#1E90FF' },
  { name: 'Ebony', hex: '#555D50' },
  { name: 'Ecru', hex: '#C2B280' },
  { name: 'Eggplant', hex: '#614051' },
  { name: 'Eggshell', hex: '#F0EAD6' },
  { name: 'Egyptian Blue', hex: '#1034A6' },
  { name: 'Electric Blue', hex: '#7DF9FF' },
  { name: 'Electric Indigo', hex: '#6F00FF' },
  { name: 'Electric Lime', hex: '#CCFF00' },
  { name: 'Electric Violet', hex: '#8F00FF' },
  { name: 'Emerald', hex: '#50C878' },
  { name: 'English Red', hex: '#AB4B52' },
  { name: 'Eucalyptus', hex: '#44D7A8' },
  { name: 'Fallow', hex: '#C19A6B' },
  { name: 'Falu Red', hex: '#801818' },
  { name: 'Fawn', hex: '#E5AA70' },
  { name: 'Feldgrau', hex: '#4D5D53' },
  { name: 'Fern Green', hex: '#4F7942' },
  { name: 'Fire Engine Red', hex: '#CE2029' },
  { name: 'Firebrick', hex: '#B22222' },
  { name: 'Flame', hex: '#E25822' },
  { name: 'Flamingo Pink', hex: '#FC8EAC' },
  { name: 'Flax', hex: '#EEED84' },
  { name: 'Floral White', hex: '#FFFAF0' },
  { name: 'Forest Green', hex: '#228B22' },
  { name: 'French Beige', hex: '#A67B5B' },
  { name: 'French Blue', hex: '#0072BB' },
  { name: 'French Lilac', hex: '#86608E' },
  { name: 'French Rose', hex: '#F64A8A' },
  { name: 'Frostbite', hex: '#E936A7' },
  { name: 'Fuchsia', hex: '#FF00FF' },
  { name: 'Fulvous', hex: '#E48400' },
  { name: 'Fuzzy Wuzzy', hex: '#CC6666' },
  { name: 'Gainsboro', hex: '#DCDCDC' },
  { name: 'Gamboge', hex: '#E49B0F' },
  { name: 'Gentian Blue', hex: '#152238' },
  { name: 'Ghost White', hex: '#F8F8FF' },
  { name: 'Glaucous', hex: '#6082B6' },
  { name: 'Gold', hex: '#FFD700' },
  { name: 'Golden Brown', hex: '#996515' },
  { name: 'Golden Poppy', hex: '#FCC200' },
  { name: 'Golden Yellow', hex: '#FFDF00' },
  { name: 'Goldenrod', hex: '#DAA520' },
  { name: 'Granite Gray', hex: '#676767' },
  { name: 'Grape', hex: '#6F2DA8' },
  { name: 'Gray', hex: '#808080' },
  { name: 'Green', hex: '#008000' },
  { name: 'Green-Yellow', hex: '#ADFF2F' },
  { name: 'Grullo', hex: '#A99A86' },
  { name: 'Gunmetal', hex: '#2A3439' },
  { name: 'Hansa Yellow', hex: '#E9D66B' },
  { name: 'Harlequin', hex: '#3FFF00' },
  { name: 'Harvest Gold', hex: '#DA9100' },
  { name: 'Heliotrope', hex: '#DF73FF' },
  { name: 'Hollywood Cerise', hex: '#F400A1' },
  { name: 'Honeydew', hex: '#F0FFF0' },
  { name: 'Honolulu Blue', hex: '#006DB0' },
  { name: 'Hooker Green', hex: '#49796B' },
  { name: 'Hot Magenta', hex: '#FF1DCE' },
  { name: 'Hot Pink', hex: '#FF69B4' },
  { name: 'Hunter Green', hex: '#355E3B' },
  { name: 'Iceberg', hex: '#71A6D2' },
  { name: 'Icterine', hex: '#FCF75E' },
  { name: 'Illuminating Emerald', hex: '#319177' },
  { name: 'Imperial Red', hex: '#ED2939' },
  { name: 'Inchworm', hex: '#B2EC5D' },
  { name: 'Indian Red', hex: '#CD5C5C' },
  { name: 'Indian Yellow', hex: '#E3A857' },
  { name: 'Indigo', hex: '#4B0082' },
  { name: 'Infrared', hex: '#FF496C' },
  { name: 'International Klein Blue', hex: '#002FA7' },
  { name: 'Iris', hex: '#5A4FCF' },
  { name: 'Irresistible', hex: '#B3446C' },
  { name: 'Isabelline', hex: '#F4F0EC' },
  { name: 'Ivory', hex: '#FFFFF0' },
  { name: 'Jade', hex: '#00A86B' },
  { name: 'Japanese Violet', hex: '#5B3256' },
  { name: 'Jasmine', hex: '#F8DE7E' },
  { name: 'Jasper', hex: '#D73B3E' },
  { name: 'Jazzberry Jam', hex: '#A50B5E' },
  { name: 'Jungle Green', hex: '#29AB87' },
  { name: 'Kelly Green', hex: '#4CBB17' },
  { name: 'Keppel', hex: '#3AB09E' },
  { name: 'Key Lime', hex: '#E8F48C' },
  { name: 'Khaki', hex: '#C3B091' },
  { name: 'Kobe', hex: '#882D17' },
  { name: 'Kobi', hex: '#E79FC4' },
  { name: 'Kobicha', hex: '#6B4423' },
  { name: 'Kombu Green', hex: '#354230' },
  { name: 'Languid Lavender', hex: '#D6CADD' },
  { name: 'Lapis Lazuli', hex: '#26619C' },
  { name: 'Laser Lemon', hex: '#FEFE22' },
  { name: 'Laurel Green', hex: '#A9BA9D' },
  { name: 'Lava', hex: '#CF1020' },
  { name: 'Lavender', hex: '#E6E6FA' },
  { name: 'Lavender Gray', hex: '#C4C3D0' },
  { name: 'Lavender Magenta', hex: '#EE82EE' },
  { name: 'Lavender Rose', hex: '#FBA0E3' },
  { name: 'Lemon', hex: '#FFF700' },
  { name: 'Lemon Chiffon', hex: '#FFFACD' },
  { name: 'Lemon Lime', hex: '#E3FF00' },
  { name: 'Licorice', hex: '#1A1110' },
  { name: 'Light Blue', hex: '#ADD8E6' },
  { name: 'Light Coral', hex: '#F08080' },
  { name: 'Light Cyan', hex: '#E0FFFF' },
  { name: 'Light Goldenrod Yellow', hex: '#FAFAD2' },
  { name: 'Light Gray', hex: '#D3D3D3' },
  { name: 'Light Green', hex: '#90EE90' },
  { name: 'Light Pink', hex: '#FFB6C1' },
  { name: 'Light Salmon', hex: '#FFA07A' },
  { name: 'Light Sea Green', hex: '#20B2AA' },
  { name: 'Light Sky Blue', hex: '#87CEFA' },
  { name: 'Light Slate Gray', hex: '#778899' },
  { name: 'Light Steel Blue', hex: '#B0C4DE' },
  { name: 'Light Yellow', hex: '#FFFFE0' },
  { name: 'Lilac', hex: '#C8A2C8' },
  { name: 'Lilac Luster', hex: '#AE98AA' },
  { name: 'Lime', hex: '#00FF00' },
  { name: 'Lime Green', hex: '#32CD32' },
  { name: 'Lincoln Green', hex: '#195905' },
  { name: 'Linen', hex: '#FAF0E6' },
  { name: 'Lion', hex: '#C19A6B' },
  { name: 'Liseran Purple', hex: '#DE6FA1' },
  { name: 'Little Boy Blue', hex: '#6F9FD2' },
  { name: 'Liver', hex: '#534B4F' },
  { name: 'Lust', hex: '#E62020' },
  { name: 'Magenta', hex: '#FF00FF' },
  { name: 'Magic Mint', hex: '#AAF0D1' },
  { name: 'Mahogany', hex: '#C04000' },
  { name: 'Maize', hex: '#FBEC5D' },
  { name: 'Malachite', hex: '#0BDA51' },
  { name: 'Manatee', hex: '#979AAA' },
  { name: 'Mandarin', hex: '#F37A48' },
  { name: 'Mango Tango', hex: '#FF8243' },
  { name: 'Mantis', hex: '#74C365' },
  { name: 'Marigold', hex: '#EAA221' },
  { name: 'Maroon', hex: '#800000' },
  { name: 'Mauve', hex: '#E0B0FF' },
  { name: 'Mauve Taupe', hex: '#915F6D' },
  { name: 'Mauvelous', hex: '#EF98AA' },
  { name: 'Maximum Blue', hex: '#47ABCC' },
  { name: 'Maximum Yellow', hex: '#FAFA37' },
  { name: 'May Green', hex: '#4C9141' },
  { name: 'Maya Blue', hex: '#73C2FB' },
  { name: 'Medium Aquamarine', hex: '#66CDAA' },
  { name: 'Medium Blue', hex: '#0000CD' },
  { name: 'Medium Candy Apple Red', hex: '#E2062C' },
  { name: 'Medium Orchid', hex: '#BA55D3' },
  { name: 'Medium Purple', hex: '#9370DB' },
  { name: 'Medium Sea Green', hex: '#3CB371' },
  { name: 'Medium Slate Blue', hex: '#7B68EE' },
  { name: 'Medium Spring Green', hex: '#00FA9A' },
  { name: 'Medium Turquoise', hex: '#48D1CC' },
  { name: 'Medium Violet Red', hex: '#C71585' },
  { name: 'Mellow Apricot', hex: '#F8B878' },
  { name: 'Melon', hex: '#FDBCB4' },
  { name: 'Metallic Seaweed', hex: '#0A7E8C' },
  { name: 'Metallic Sunburst', hex: '#9C7C38' },
  { name: 'Midnight Blue', hex: '#191970' },
  { name: 'Midnight Green', hex: '#004953' },
  { name: 'Mikado Yellow', hex: '#FFC40C' },
  { name: 'Mimi Pink', hex: '#FFDAE9' },
  { name: 'Mindaro', hex: '#E3F988' },
  { name: 'Ming', hex: '#36747D' },
  { name: 'Minion Yellow', hex: '#F5E050' },
  { name: 'Mint', hex: '#3EB489' },
  { name: 'Mint Cream', hex: '#F5FFFA' },
  { name: 'Mint Green', hex: '#98FF98' },
  { name: 'Misty Rose', hex: '#FFE4E1' },
  { name: 'Moccasin', hex: '#FFE4B5' },
  { name: 'Modena', hex: '#46244C' },
  { name: 'Mode Beige', hex: '#967117' },
  { name: 'Mona Lisa', hex: '#FF9889' },
  { name: 'Monarch', hex: '#8B0000' },
  { name: 'Mulberry', hex: '#C54B8C' },
  { name: 'Mustard', hex: '#FFDB58' },
  { name: 'Myrtle Green', hex: '#317873' },
  { name: 'Nadir Blue', hex: '#1D3B58' },
  { name: 'Naples Yellow', hex: '#FADA5E' },
  { name: 'Navajo White', hex: '#FFDEAD' },
  { name: 'Navy Blue', hex: '#000080' },
  { name: 'Neon Carrot', hex: '#FFA343' },
  { name: 'Neon Green', hex: '#39FF14' },
  { name: 'New York Pink', hex: '#D7837F' },
  { name: 'Nickel', hex: '#727472' },
  { name: 'Non-Photo Blue', hex: '#A4DDED' },
  { name: 'Nyanza', hex: '#E9FFDB' },
  { name: 'Ocean Blue', hex: '#4F42B5' },
  { name: 'Ocean Green', hex: '#48BF91' },
  { name: 'Ochre', hex: '#CC7722' },
  { name: 'Old Gold', hex: '#CFB53B' },
  { name: 'Old Lace', hex: '#FDF5E6' },
  { name: 'Old Lavender', hex: '#796878' },
  { name: 'Old Mauve', hex: '#673147' },
  { name: 'Old Rose', hex: '#C08081' },
  { name: 'Olive', hex: '#808000' },
  { name: 'Olive Drab', hex: '#6B8E23' },
  { name: 'Olive Green', hex: '#B5B35C' },
  { name: 'Olivine', hex: '#9AB973' },
  { name: 'Onyx', hex: '#353839' },
  { name: 'Opal', hex: '#A8C3BC' },
  { name: 'Opera Mauve', hex: '#B784A7' },
  { name: 'Orange', hex: '#FFA500' },
  { name: 'Orange-Red', hex: '#FF4500' },
  { name: 'Orange Soda', hex: '#FA5B3D' },
  { name: 'Orchid', hex: '#DA70D6' },
  { name: 'Orchid Pink', hex: '#F2BDCD' },
  { name: 'Orioles Orange', hex: '#FC4C02' },
  { name: 'Outrageous Orange', hex: '#FF6E4A' },
  { name: 'Oxblood', hex: '#800020' },
  { name: 'Pacific Blue', hex: '#1CA9C9' },
  { name: 'Pakistan Green', hex: '#006600' },
  { name: 'Palatinate Purple', hex: '#682860' },
  { name: 'Pale Aqua', hex: '#BCD4E6' },
  { name: 'Pale Cerulean', hex: '#98B4D4' },
  { name: 'Pale Gold', hex: '#E6C280' },
  { name: 'Pale Goldenrod', hex: '#EEE8AA' },
  { name: 'Pale Green', hex: '#98FB98' },
  { name: 'Pale Lavender', hex: '#DCD0FF' },
  { name: 'Pale Magenta', hex: '#F984E5' },
  { name: 'Pale Pink', hex: '#FADADD' },
  { name: 'Pale Plum', hex: '#DDA0DD' },
  { name: 'Pale Red-Violet', hex: '#DB7093' },
  { name: 'Pale Robin Egg Blue', hex: '#96DED1' },
  { name: 'Pale Spring Bud', hex: '#ECEBBD' },
  { name: 'Pale Turquoise', hex: '#AFEEEE' },
  { name: 'Pansy Purple', hex: '#78184A' },
  { name: 'Papaya Whip', hex: '#FFEFD5' },
  { name: 'Paradise Pink', hex: '#E63E62' },
  { name: 'Parchment', hex: '#F1E9D2' },
  { name: 'Paris Green', hex: '#50C878' },
  { name: 'Pastel Blue', hex: '#AEC6CF' },
  { name: 'Pastel Gray', hex: '#CFD8DC' },
  { name: 'Pastel Green', hex: '#77DD77' },
  { name: 'Pastel Magenta', hex: '#F49AC2' },
  { name: 'Pastel Orange', hex: '#FFB347' },
  { name: 'Pastel Pink', hex: '#FFD1DC' },
  { name: 'Pastel Purple', hex: '#B39EB5' },
  { name: 'Pastel Red', hex: '#FF6961' },
  { name: 'Pastel Violet', hex: '#CB99C9' },
  { name: 'Pastel Yellow', hex: '#FDFD96' },
  { name: 'Peach', hex: '#FFE5B4' },
  { name: 'Peach Puff', hex: '#FFDAB9' },
  { name: 'Pear', hex: '#D1E231' },
  { name: 'Pearl', hex: '#EAE0C8' },
  { name: 'Pearl Aqua', hex: '#88D8C0' },
  { name: 'Periwinkle', hex: '#CCCCFF' },
  { name: 'Permanent Geranium Lake', hex: '#E12C2C' },
  { name: 'Persian Blue', hex: '#1C39BB' },
  { name: 'Persian Green', hex: '#00A693' },
  { name: 'Persian Indigo', hex: '#32127A' },
  { name: 'Persian Orange', hex: '#D99058' },
  { name: 'Persian Pink', hex: '#F77FBE' },
  { name: 'Persian Plum', hex: '#701C1C' },
  { name: 'Persian Red', hex: '#CC3333' },
  { name: 'Persian Rose', hex: '#FE28A2' },
  { name: 'Persimmon', hex: '#EC5800' },
  { name: 'Peruvian Lily', hex: '#E6A221' },
  { name: 'Phthalo Blue', hex: '#000F89' },
  { name: 'Phthalo Green', hex: '#123524' },
  { name: 'Picotte Indigo', hex: '#4B365B' },
  { name: 'Piggy Pink', hex: '#FDDDE6' },
  { name: 'Pine Green', hex: '#01796F' },
  { name: 'Pineapple', hex: '#563C0D' },
  { name: 'Pink', hex: '#FFC0CB' },
  { name: 'Pink Flamingo', hex: '#FC74FD' },
  { name: 'Pink Lace', hex: '#FFDDF4' },
  { name: 'Pink Lavender', hex: '#D8B2D1' },
  { name: 'Pink Sherbet', hex: '#F78FA7' },
  { name: 'Pistachio', hex: '#93C572' },
  { name: 'Platinum', hex: '#E5E4E2' },
  { name: 'Plum', hex: '#DDA0DD' },
  { name: 'Plump Purple', hex: '#5946B2' },
  { name: 'Polished Pine', hex: '#5DA493' },
  { name: 'Pomegranate', hex: '#C0392B' },
  { name: 'Pompadour', hex: '#350036' },
  { name: 'Portland Orange', hex: '#FF5A36' },
  { name: 'Powder Blue', hex: '#B0E0E6' },
  { name: 'Princess Perfume', hex: '#FF85CF' },
  { name: 'Prussian Blue', hex: '#003153' },
  { name: 'Psychedelic Purple', hex: '#DF00FF' },
  { name: 'Puce', hex: '#CC8899' },
  { name: 'Pumpkin', hex: '#FF7518' },
  { name: 'Purple', hex: '#800080' },
  { name: 'Purple Heart', hex: '#69359C' },
  { name: 'Purple Mountain Majesty', hex: '#9678B6' },
  { name: 'Purple Pizzazz', hex: '#FE4EDA' },
  { name: 'Purple Taupe', hex: '#50404D' },
  { name: 'Quartz', hex: '#51484F' },
  { name: 'Queen Blue', hex: '#436B95' },
  { name: 'Queen Pink', hex: '#E8CCD7' },
  { name: 'Quick Silver', hex: '#A6A6A6' },
  { name: 'Radical Red', hex: '#FF355E' },
  { name: 'Raisin Black', hex: '#242124' },
  { name: 'Rajah', hex: '#FBAB60' },
  { name: 'Raspberry', hex: '#E30B5D' },
  { name: 'Raw Sienna', hex: '#D68A59' },
  { name: 'Raw Umber', hex: '#826644' },
  { name: 'Razzle Dazzle Rose', hex: '#FF33CC' },
  { name: 'Razzmatazz', hex: '#E3256B' },
  { name: 'Razzmic Berry', hex: '#8D4E85' },
  { name: 'Rebecca Purple', hex: '#663399' },
  { name: 'Red', hex: '#FF0000' },
  { name: 'Red-Orange', hex: '#FF5349' },
  { name: 'Red-Purple', hex: '#E40078' },
  { name: 'Red-Violet', hex: '#C71585' },
  { name: 'Redwood', hex: '#A45A52' },
  { name: 'Regalia', hex: '#522D80' },
  { name: 'Resolution Blue', hex: '#002387' },
  { name: 'Rhythm', hex: '#777696' },
  { name: 'Rich Black', hex: '#004040' },
  { name: 'Rich Lavender', hex: '#A76BCF' },
  { name: 'Rich Lilac', hex: '#B666D2' },
  { name: 'Rich Maroon', hex: '#B03060' },
  { name: 'Rifle Green', hex: '#414833' },
  { name: 'Robin Egg Blue', hex: '#00CCCC' },
  { name: 'Rocket Metallic', hex: '#8E7F7F' },
  { name: 'Roman Silver', hex: '#838996' },
  { name: 'Rose', hex: '#FF007F' },
  { name: 'Rose Bonbon', hex: '#F9429E' },
  { name: 'Rose Dust', hex: '#9E5E6F' },
  { name: 'Rose Gold', hex: '#B76E79' },
  { name: 'Rose Madder', hex: '#E32636' },
  { name: 'Rose Pink', hex: '#FF66CC' },
  { name: 'Rose Quartz', hex: '#AA98A9' },
  { name: 'Rose Red', hex: '#C21E56' },
  { name: 'Rose Vale', hex: '#AB4E52' },
  { name: 'Rosewood', hex: '#65000B' },
  { name: 'Rosy Brown', hex: '#BC8F8F' },
  { name: 'Royal Blue', hex: '#4169E1' },
  { name: 'Royal Purple', hex: '#7851A9' },
  { name: 'Rubine Red', hex: '#D10056' },
  { name: 'Ruby', hex: '#E0115F' },
  { name: 'Ruby Red', hex: '#9B111E' },
  { name: 'Rufous', hex: '#A81C07' },
  { name: 'Russet', hex: '#80461B' },
  { name: 'Russian Violet', hex: '#32174D' },
  { name: 'Rust', hex: '#B7410E' },
  { name: 'Saddle Brown', hex: '#8B4513' },
  { name: 'Safety Orange', hex: '#FF6700' },
  { name: 'Saffron', hex: '#F4C430' },
  { name: 'Sage', hex: '#BCB88A' },
  { name: 'Salmon', hex: '#FA8072' },
  { name: 'Salmon Pink', hex: '#FF91A4' },
  { name: 'Sand', hex: '#C2B280' },
  { name: 'Sandstorm', hex: '#ECD540' },
  { name: 'Sandy Brown', hex: '#F4A460' },
  { name: 'Sap Green', hex: '#507D2A' },
  { name: 'Sapphire', hex: '#0F52BA' },
  { name: 'Sapphire Blue', hex: '#0067A5' },
  { name: 'Satin Sheen Gold', hex: '#CBA135' },
  { name: 'Scarlet', hex: '#FF2400' },
  { name: 'Schauss Pink', hex: '#FF91AF' },
  { name: 'School Bus Yellow', hex: '#FFD800' },
  { name: 'Screamin Green', hex: '#66FF66' },
  { name: 'Sea Green', hex: '#2E8B57' },
  { name: 'Seafoam Green', hex: '#9FE2BF' },
  { name: 'Seal Brown', hex: '#59260B' },
  { name: 'Seashell', hex: '#FFF5EE' },
  { name: 'Selective Yellow', hex: '#FFBA00' },
  { name: 'Sepia', hex: '#704214' },
  { name: 'Shadow', hex: '#8A795D' },
  { name: 'Shadow Blue', hex: '#778BA5' },
  { name: 'Shamrock Green', hex: '#009E60' },
  { name: 'Sheen Green', hex: '#8FD400' },
  { name: 'Shimmering Blush', hex: '#D98695' },
  { name: 'Shiny Shamrock', hex: '#5FA777' },
  { name: 'Shocking Pink', hex: '#FC0FC0' },
  { name: 'Sienna', hex: '#A0522D' },
  { name: 'Silver', hex: '#C0C0C0' },
  { name: 'Silver Chalice', hex: '#ACACAC' },
  { name: 'Silver Pink', hex: '#C4AEAD' },
  { name: 'Silver Sand', hex: '#BFC1C2' },
  { name: 'Sinopia', hex: '#CB410B' },
  { name: 'Sizzling Red', hex: '#FF3855' },
  { name: 'Sizzling Tangerine', hex: '#FF7124' },
  { name: 'Skobeloff', hex: '#007474' },
  { name: 'Sky Blue', hex: '#87CEEB' },
  { name: 'Sky Magenta', hex: '#CF71AF' },
  { name: 'Slate Blue', hex: '#6A5ACD' },
  { name: 'Slate Gray', hex: '#708090' },
  { name: 'Slimy Green', hex: '#299617' },
  { name: 'Smitten', hex: '#C84186' },
  { name: 'Smoke', hex: '#738276' },
  { name: 'Smoky Black', hex: '#100C08' },
  { name: 'Snow', hex: '#FFFAFA' },
  { name: 'Solid Pink', hex: '#893843' },
  { name: 'Sonic Silver', hex: '#757575' },
  { name: 'Space Cadet', hex: '#1D2951' },
  { name: 'Spanish Bistro', hex: '#806020' },
  { name: 'Spanish Blue', hex: '#0070B8' },
  { name: 'Spanish Carmine', hex: '#D10047' },
  { name: 'Spanish Gray', hex: '#989898' },
  { name: 'Spanish Green', hex: '#009150' },
  { name: 'Spanish Orange', hex: '#E86100' },
  { name: 'Spanish Pink', hex: '#F7BFBE' },
  { name: 'Spanish Red', hex: '#E60026' },
  { name: 'Spanish Violet', hex: '#4C2882' },
  { name: 'Spanish Viridian', hex: '#007F5C' },
  { name: 'Spicy Mix', hex: '#8B5A2B' },
  { name: 'Spiro Disco Ball', hex: '#0FC0FC' },
  { name: 'Spring Bud', hex: '#A7FC00' },
  { name: 'Spring Green', hex: '#00FF7F' },
  { name: 'Steel Blue', hex: '#4682B4' },
  { name: 'Steel Pink', hex: '#CC33CC' },
  { name: 'Steel Teal', hex: '#5F8A8B' },
  { name: 'Straw', hex: '#E4D96F' },
  { name: 'Strawberry', hex: '#FC5A8D' },
  { name: 'Sugar Plum', hex: '#914E75' },
  { name: 'Sunburst', hex: '#FF4500' },
  { name: 'Sunflower', hex: '#FFDA29' },
  { name: 'Sunset', hex: '#FAD6A5' },
  { name: 'Sunset Orange', hex: '#FD5E53' },
  { name: 'Sweet Brown', hex: '#A83731' },
  { name: 'Tangerine', hex: '#F28500' },
  { name: 'Tangerine Yellow', hex: '#FFCC00' },
  { name: 'Tango Pink', hex: '#E4717A' },
  { name: 'Taupe', hex: '#483C32' },
  { name: 'Taupe Gray', hex: '#8B8589' },
  { name: 'Tea Green', hex: '#D0F0C0' },
  { name: 'Tea Rose', hex: '#F4C2C2' },
  { name: 'Teal', hex: '#008080' },
  { name: 'Teal Blue', hex: '#367588' },
  { name: 'Teal Green', hex: '#00827F' },
  { name: 'Telemagenta', hex: '#CF3476' },
  { name: 'Tenné', hex: '#CD5700' },
  { name: 'Terracotta', hex: '#E2725B' },
  { name: 'Thistle', hex: '#D8BFD8' },
  { name: 'Thulian Pink', hex: '#DE6FA1' },
  { name: 'Tickle Me Pink', hex: '#FC89AC' },
  { name: 'Tiffany Blue', hex: '#0ABAB5' },
  { name: 'Tiger Eye', hex: '#B56917' },
  { name: 'Timberwolf', hex: '#DBD7D2' },
  { name: 'Titanium Yellow', hex: '#EEE600' },
  { name: 'Tomato', hex: '#FF6347' },
  { name: 'Toolbox', hex: '#746CC0' },
  { name: 'Topaz', hex: '#FFC87C' },
  { name: 'Tractor Red', hex: '#FD0E35' },
  { name: 'Trolley Grey', hex: '#808080' },
  { name: 'Tropical Rain Forest', hex: '#00755E' },
  { name: 'Tropical Violet', hex: '#CDA4DE' },
  { name: 'Tufts Blue', hex: '#417DC1' },
  { name: 'Tulip', hex: '#FF878D' },
  { name: 'Tumbleweed', hex: '#DEAA88' },
  { name: 'Turkish Rose', hex: '#B57281' },
  { name: 'Turquoise', hex: '#40E0D0' },
  { name: 'Turquoise Blue', hex: '#00FFEF' },
  { name: 'Turquoise Green', hex: '#A0D6B4' },
  { name: 'Tuscan Red', hex: '#7C3030' },
  { name: 'Tuscany', hex: '#C94A29' },
  { name: 'Twilight Lavender', hex: '#8A496B' },
  { name: 'Tyrian Purple', hex: '#66023C' },
  { name: 'UA Blue', hex: '#0033AA' },
  { name: 'UA Red', hex: '#D9004C' },
  { name: 'Ube', hex: '#8878C0' },
  { name: 'UCLA Blue', hex: '#2774AE' },
  { name: 'UCLA Gold', hex: '#FFC72C' },
  { name: 'UFO Green', hex: '#3CD070' },
  { name: 'Ultramarine', hex: '#120A8F' },
  { name: 'Ultramarine Blue', hex: '#4166F5' },
  { name: 'Ultra Pink', hex: '#FF6FFF' },
  { name: 'Ultra Red', hex: '#FC6C85' },
  { name: 'Umber', hex: '#635147' },
  { name: 'Unbleached Silk', hex: '#FFDDCA' },
  { name: 'United Nations Blue', hex: '#5B92E5' },
  { name: 'University of California Gold', hex: '#B78727' },
  { name: 'Unmellow Yellow', hex: '#FFFF66' },
  { name: 'UP Forest Green', hex: '#014421' },
  { name: 'UP Maroon', hex: '#7B1113' },
  { name: 'Upsdell Red', hex: '#AE2029' },
  { name: 'Urobilin', hex: '#E1AD21' },
  { name: 'USAFA Blue', hex: '#004F98' },
  { name: 'USC Cardinal', hex: '#990000' },
  { name: 'USC Gold', hex: '#FFCC00' },
  { name: 'University of Tennessee Orange', hex: '#F77F00' },
  { name: 'Utah Crimson', hex: '#CC0033' },
  { name: 'Valencia', hex: '#D84B20' },
  { name: 'Van Dyke Brown', hex: '#664228' },
  { name: 'Vanilla', hex: '#F3E5AB' },
  { name: 'Vanilla Ice', hex: '#F38FA9' },
  { name: 'Vegas Gold', hex: '#C5B358' },
  { name: 'Venetian Red', hex: '#C80815' },
  { name: 'Verdigris', hex: '#43B3AE' },
  { name: 'Vermilion', hex: '#E34234' },
  { name: 'Veronica', hex: '#A020F0' },
  { name: 'Very Light Blue', hex: '#6666FF' },
  { name: 'Very Light Orchid', hex: '#E6A8D7' },
  { name: 'Very Light Tangelo', hex: '#FFB077' },
  { name: 'Very Pale Orange', hex: '#FFDFD3' },
  { name: 'Very Pale Yellow', hex: '#FFFFBF' },
  { name: 'Violet', hex: '#8F00FF' },
  { name: 'Violet-Blue', hex: '#324AB2' },
  { name: 'Violet-Red', hex: '#F75394' },
  { name: 'Viridian', hex: '#40826D' },
  { name: 'Viridian Green', hex: '#009698' },
  { name: 'Vista Blue', hex: '#7C9D96' },
  { name: 'Vivid Amber', hex: '#CC9900' },
  { name: 'Vivid Auburn', hex: '#922724' },
  { name: 'Vivid Burgundy', hex: '#9F1D35' },
  { name: 'Vivid Cerise', hex: '#DA1D5F' },
  { name: 'Vivid Tangerine', hex: '#FFA089' },
  { name: 'Vivid Violet', hex: '#9F00FF' },
  { name: 'Volt', hex: '#CEFF00' },
  { name: 'Warm Black', hex: '#004242' },
  { name: 'Watermelon', hex: '#FC6C85' },
  { name: 'Weldon Blue', hex: '#7C98AB' },
  { name: 'Wenge', hex: '#645452' },
  { name: 'Wheat', hex: '#F5DEB3' },
  { name: 'White', hex: '#FFFFFF' },
  { name: 'White Smoke', hex: '#F5F55F' },
  { name: 'Wild Blue Yonder', hex: '#A2ADD0' },
  { name: 'Wild Orchid', hex: '#D470A2' },
  { name: 'Wild Strawberry', hex: '#FF43A4' },
  { name: 'Wild Watermelon', hex: '#FC6C85' },
  { name: 'Windsor Tan', hex: '#A75502' },
  { name: 'Wine', hex: '#722F37' },
  { name: 'Wine Dregs', hex: '#673147' },
  { name: 'Winter Sky', hex: '#FF007F' },
  { name: 'Wintergreen Dream', hex: '#56887D' },
  { name: 'Wisteria', hex: '#C9A0DC' },
  { name: 'Wood Brown', hex: '#C19A6B' },
  { name: 'Xanadu', hex: '#738678' },
  { name: 'Yale Blue', hex: '#0F4D92' },
  { name: 'Yankees Blue', hex: '#1C2841' },
  { name: 'Yellow', hex: '#FFFF00' },
  { name: 'Yellow-Green', hex: '#9ACD32' },
  { name: 'Yellow Munsell', hex: '#EFCC00' },
  { name: 'Yellow Orange', hex: '#FFAE42' },
  { name: 'Yellow Sunshine', hex: '#FFF700' },
  { name: 'Zaffre', hex: '#0014A8' },
  { name: 'Zinnwaldite Brown', hex: '#2C1603' },
  { name: 'Zomp', hex: '#39A78E' }
];

export function getNearestColorName(hex: string): string {
  const rgb = hexToRgb(hex);
  let minDistance = Infinity;
  let nearestName = 'Unknown';

  for (const item of COLOR_DICTIONARY) {
    const itemRgb = hexToRgb(item.hex);
    
    // Using weighted Euclidean distance to better align with human color perception
    // D = sqrt(2*dR^2 + 4*dG^2 + 3*dB^2)
    const dR = rgb.r - itemRgb.r;
    const dG = rgb.g - itemRgb.g;
    const dB = rgb.b - itemRgb.b;
    
    const distance = 2 * dR * dR + 4 * dG * dG + 3 * dB * dB;
    
    if (distance < minDistance) {
      minDistance = distance;
      nearestName = item.name;
    }
  }

  return nearestName;
}
